export const START_HERE = `# Agent Workbench

This directory is the user's working environment. It may contain several
related source projects under \`src/\`.

## Operating model

1. Work from the workspace root, not from a single source repository.
2. Identify the task, active role, and involved projects before loading context.
3. Read only the role, workflow, project knowledge, and relationship information
   needed for the current task.
4. Treat task read and write scopes as the work boundary. Relationships supply
   context, but never silently grant access to another project.
5. Use available \`awb\` commands when structured workspace information is
   needed. Do not scan all knowledge speculatively.
6. Read full knowledge content only after selecting a relevant knowledge ID.
7. External knowledge providers are optional derived recall. Call them only
   when a bound task needs them; never treat a provider response as canonical.
8. Register deliverables as artifacts, complete the required quality gates, and
   verify the task before closing it.
9. Record reusable observations as memory proposals. Do not promote them to
   durable knowledge without user approval.
10. A harness may create its own native instruction file if it needs one. Such a
   file is only an entry point and must not duplicate the whole workspace.

## Standard directories

- \`user/\`: stable user profile and working principles.
- \`roles/\`: role-specific rules and definitions of done.
- \`projects/\`: project registry.
- \`relationships/\`: typed relationships between projects.
- \`knowledge/\`: indexed, durable Markdown knowledge.
- \`knowledge/providers.json\`: optional provider endpoints and project bindings;
  credentials remain runtime-only.
- \`skills/\`: reusable skills, added directly by skill ID.
- \`workflows/\`: reusable workflows, added directly by workflow ID.
- \`work/\`: task contracts, artifact records, and learning proposals.
- \`src/\`: managed sources, Git submodules, or external-source references.
- \`profile/\`: generated human-facing HTML profile.

## Compact context flow

\`awb task context <task-id>\` returns compact references. Use
\`awb knowledge read <knowledge-id>\` only for items that are relevant.
Use \`awb provider recall <query> --project <id>\` only when a task needs
external recall.
`;

export const USER_PROFILE = `# User Profile

Describe the user whose working point of view this workspace represents.

## About

- Name:
- Primary responsibilities:
- Preferred language:

## Working principles

- Add durable principles here.

## Communication preferences

- Add communication preferences here.
`;

export const DIRECTORY_READMES = {
  roles: `# Roles

Add a role directly as \`roles/<role-id>/\`. A role directory may contain files
such as \`ROLE.md\`, \`RULES.md\`, and \`DEFINITION_OF_DONE.md\`.
`,
  skills: `# Skills

Add a skill directly as \`skills/<skill-id>/\`. Prefer the native Agent Skills
layout with a \`SKILL.md\` file when the target harness supports it.
`,
  workflows: `# Workflows

Add a workflow directly as \`workflows/<workflow-id>/\`. Keep the workflow
deterministic where possible and link the skills it uses.
`,
  knowledge: `# Knowledge

Durable knowledge bodies live in \`knowledge/items/\` and are registered by
stable ID in \`knowledge/index.json\`. Use the CLI so the body and index stay in
sync. Optional external recall providers and their project bindings live in
\`knowledge/providers.json\`. Provider output must enter \`work/proposals/\`
before it can become approved knowledge.
`,
  src: `# Sources

Keep all user project entry points here and register each one with
\`awb project add\`. A project may be a managed folder, a Git submodule, or a
portable descriptor whose machine-local path is stored in \`src/.external/\`.
`,
  profile: `# Profile

\`index.html\` is generated by \`awb profile build\`. It is a human-facing view,
not a canonical data source.
`
};
