export const START_HERE = `# Agent Workbench

This directory is the user's working environment. It may contain several
related source projects under \`src/\`.

## Operating model

1. Run \`awb profile status\`. If it reports that onboarding is not complete,
   interview the user with the questions it returns before starting any task,
   then record the answers with \`awb profile complete\`. Do not guess who the
   user is or which skills apply.
2. Work from the workspace root, not from a single source repository.
3. Identify the task, active role, and involved projects before loading context.
4. Read only the role, workflow, project knowledge, and relationship information
   needed for the current task.
5. Treat task read and write scopes as the work boundary. Relationships supply
   context, but never silently grant access to another project.
6. Use available \`awb\` commands when structured workspace information is
   needed. Do not scan all knowledge speculatively.
7. Read full knowledge content only after selecting a relevant knowledge ID.
8. External knowledge providers are optional derived recall. Call them only
   when a bound task needs them; never treat a provider response as canonical.
9. Register deliverables as artifacts, complete the required quality gates, and
   verify the task before closing it.
10. Record reusable observations as memory proposals. Do not promote them to
   durable knowledge without user approval.
11. A harness may create its own native instruction file if it needs one. Such a
   file is only an entry point and must not duplicate the whole workspace.

## Standard directories

- \`user/\`: stable user profile and working principles.
- \`roles/\`: role-specific rules and definitions of done.
- \`projects/\`: project registry.
- \`relationships/\`: typed relationships between projects.
- \`knowledge/\`: indexed, durable Markdown knowledge.
- \`knowledge/providers.json\`: optional provider endpoints and project bindings;
  credentials remain runtime-only.
- \`skills/\`: reusable skills, added directly by skill ID.
- \`workflows/\`: reusable workflows, added directly by workflow ID.
- \`work/\`: task contracts, artifact records, and learning proposals.
- \`src/\`: managed sources, Git submodules, or external-source references.
- \`profile/\`: generated human-facing HTML profile.

## Compact context flow

\`awb task context <task-id>\` returns compact references. Use
\`awb knowledge read <knowledge-id>\` only for items that are relevant.
Use \`awb provider recall <query> --project <id>\` only when a task needs
external recall.
`;

export const USER_PROFILE = `# User Profile

Describe the user whose working point of view this workspace represents.

## About

- Name:
- Primary responsibilities:
- Preferred language:

## Working principles

- Add durable principles here.

## Communication preferences

- Add communication preferences here.
`;

export const DIRECTORY_READMES = {
  roles: `# Roles

Add a role directly as \`roles/<role-id>/\`. A role directory may contain files
such as \`ROLE.md\`, \`RULES.md\`, and \`DEFINITION_OF_DONE.md\`.
`,
  skills: `# Skills

Add a skill directly as \`skills/<skill-id>/\`. Prefer the native Agent Skills
layout with a \`SKILL.md\` file when the target harness supports it.
`,
  workflows: `# Workflows

Add a workflow directly as \`workflows/<workflow-id>/\`. Keep the workflow
deterministic where possible and link the skills it uses.
`,
  knowledge: `# Knowledge

Durable knowledge bodies live in \`knowledge/items/\` and are registered by
stable ID in \`knowledge/index.json\`. Use the CLI so the body and index stay in
sync. Optional external recall providers and their project bindings live in
\`knowledge/providers.json\`. Provider output must enter \`work/proposals/\`
before it can become approved knowledge.
`,
  src: `# Sources

Keep all user project entry points here and register each one with
\`awb project add\`. A project may be a managed folder, a Git submodule, or a
portable descriptor whose machine-local path is stored in \`src/.external/\`.
`,
  profile: `# Profile

\`index.html\` is generated by \`awb profile build\`. It is a human-facing view,
not a canonical data source.
`
};

// A starter catalog, not a finished taxonomy. A workspace owner is expected to
// edit these and add their own; they exist so that a fresh workspace has real
// capabilities to route to instead of three empty directories.
export const CAPABILITY_CATALOG = {
  "roles/developer/ROLE.md": `# Role: Developer

Builds and changes software in the registered projects.

## Responsibilities

- Understand the task scope before editing anything.
- Stay inside the task's write scope. Read access to a related project is not
  permission to change it.
- Prefer the smallest change that solves the stated problem.

## Expected outputs

- Source changes registered as artifacts.
- A short account of what was verified and how.
`,
  "roles/developer/DEFINITION_OF_DONE.md": `# Definition of Done: Developer

- The change does what the task objective describes.
- Automated tests covering the change pass, and the output was seen, not assumed.
- No credential, token, or connection string entered the workspace.
- Every deliverable is registered as an artifact and marked verified.
- Every quality gate on the task has passed.
`,
  "roles/reviewer/ROLE.md": `# Role: Reviewer

Reviews work produced by others against the task contract.

## Responsibilities

- Check the change against the task objective and definition of done.
- Report defects with a concrete failing case, not a general impression.
- Separate correctness problems from preferences, and say which is which.

## Expected outputs

- A findings list, most severe first.
- An explicit verdict on each quality gate the review covers.
`,
  "roles/reviewer/DEFINITION_OF_DONE.md": `# Definition of Done: Reviewer

- Every finding names a file, a line, and a way to reproduce it.
- Findings that could not be verified are labelled as unverified.
- The review states plainly whether the task may close.
`,
  "roles/technical-writer/ROLE.md": `# Role: Technical Writer

Produces documentation for a stated audience.

## Responsibilities

- Confirm who the reader is before writing; the task's audience field is the
  contract.
- Describe what the system does, verified against the system, not the ticket.
- Keep internal details out of user-facing documents.

## Expected outputs

- A document registered as an artifact.
- The audience it was written for.
`,
  "roles/technical-writer/DEFINITION_OF_DONE.md": `# Definition of Done: Technical Writer

- The document names its audience and stays at that audience's level.
- Every instruction was checked against the running system.
- No internal hostname, credential, or customer name appears in the text.
`,
  "skills/code-review/SKILL.md": `# Skill: Code Review

Use when reviewing a change before it merges.

## Method

1. Read the task objective first, then the diff. A change that is correct but
   unrelated to the objective is still a finding.
2. For each suspected defect, construct the input that triggers it. If you
   cannot, label the finding unverified rather than dropping or asserting it.
3. Rank by severity: wrong results first, then crashes, then maintainability.

## Output

A findings list. Each entry: file, line, what breaks, and the failing case.
`,
  "skills/code-review/skill.json": `{
  "id": "code-review",
  "title": "Code Review",
  "useWhen": "Reviewing a change before it merges.",
  "inputs": ["the task objective", "the diff under review"],
  "outputs": ["a findings list ranked by severity"],
  "verify": ["every finding names a file, a line, and a failing case"]
}
`,
  "skills/debugging/SKILL.md": `# Skill: Debugging

Use when something fails and the cause is not yet known.

## Method

1. Reproduce the failure and keep the exact reproduction command.
2. Read the actual error output before forming a theory.
3. Form one hypothesis, then find the cheapest observation that would disprove
   it. Change one thing at a time.
4. Fix the cause, not the symptom. If you only know how to hide the symptom,
   say so.

## Output

The reproduction, the cause, the fix, and the evidence the fix works.
`,
  "skills/debugging/skill.json": `{
  "id": "debugging",
  "title": "Debugging",
  "useWhen": "Something fails and the cause is not yet known.",
  "inputs": ["a reproduction of the failure"],
  "outputs": ["the cause", "the fix", "evidence the fix works"],
  "verify": ["the reproduction no longer fails", "the cause was fixed, not the symptom"]
}
`,
  "skills/writing-user-guide/SKILL.md": `# Skill: Writing a User Guide

Use when producing instructions for someone who does not build the system.

## Method

1. Name the audience and the single task the guide accomplishes.
2. Perform the task yourself in the real system, recording each step.
3. Write the steps in the order the reader performs them, with the visible
   result of each step so the reader can tell whether it worked.
4. Cut anything the reader does not need to finish the task.

## Output

A document whose steps a reader can follow start to finish without help.
`,
  "skills/writing-user-guide/skill.json": `{
  "id": "writing-user-guide",
  "title": "Writing a User Guide",
  "useWhen": "Producing instructions for someone who does not build the system.",
  "inputs": ["the audience", "the single task the guide accomplishes"],
  "outputs": ["a document a reader can follow start to finish"],
  "verify": ["every step was performed in the real system before it was written"]
}
`,
  "skills/research/SKILL.md": `# Skill: Research

Use before committing to an approach you do not yet understand.

## Method

1. Write the question down first, in one sentence, and bound it: what answer
   would let you stop looking?
2. Record the plan before searching. A plan you cannot write is a question you
   have not narrowed enough.
3. Try one thing at a time and record every attempt, **especially the ones that
   fail**. "Polling returned 429 after 40 requests" is the finding; the working
   approach is only half the value.
4. Stop when the question is answered, not when something works. Those differ.
5. Conclude into a proposal so the person decides whether it becomes knowledge.

## Commands

\`\`\`bash
awb research start --question "..." --plan "..."
awb research attempt <id> --tried "..." --result failed --note "..."
awb research conclude <id> --text "..."
\`\`\`

## Output

An answered question, an attempt log the next person can read, and a proposal
awaiting approval.
`,
  "skills/research/skill.json": `{
  "id": "research",
  "title": "Research",
  "useWhen": "You must understand something before you can decide how to build it.",
  "inputs": ["a question worth bounding"],
  "outputs": ["an attempt log including the failures", "a conclusion proposed for approval"],
  "verify": ["the question is answered, not merely worked around", "every failed attempt is recorded"]
}
`,
  "skills/api-integration/SKILL.md": `# Skill: API Integration

Use when connecting our system to a third-party API.

## Method

1. Read the API documentation first and record the authentication method, the
   rate limits, and how pagination works.
2. Get one read call working before building anything on top of it.
3. Keep keys and tokens in environment variables. Nothing secret enters the
   workspace.
4. Handle pagination and retry before calling the integration done.

## Output

A working client, and the limits you found written down where the next person
will look.
`,
  "skills/api-integration/skill.json": `{
  "id": "api-integration",
  "title": "API Integration",
  "useWhen": "Connecting our system to a third-party API.",
  "inputs": ["API documentation", "the authentication method"],
  "outputs": ["a working client", "recorded rate limits and pagination rules"],
  "verify": ["one real read call succeeds", "no credential was written into the workspace"]
}
`,
  "workflows/feature-delivery/WORKFLOW.md": `# Workflow: Feature Delivery

1. \`awb task create\` with the role, projects, deliverables, and quality gates.
2. \`awb task context <task-id>\` to load scoped context.
3. Build the change inside the task write scope.
4. Verify: run the tests and read the output.
5. \`awb artifact add\` for each deliverable, with \`--verified\` once checked.
6. \`awb task gate-pass\` for each quality gate.
7. \`awb task verify\`, then \`awb task close\`.
8. \`awb memory propose\` for anything reusable that was learned.
`,
  "workflows/document-delivery/WORKFLOW.md": `# Workflow: Document Delivery

1. \`awb task create\` with the technical-writer role and an explicit
   \`--audience\`.
2. \`awb task context <task-id>\` and read the project knowledge it names.
3. Perform the documented task in the real system before writing about it.
4. Write the document into the task write scope.
5. \`awb artifact add\` with \`--kind\` matching the declared deliverable.
6. \`awb task gate-pass\` for review and sensitive-data checks.
7. \`awb task verify\`, then \`awb task close\`.
`,
  "workflows/research-to-skill/WORKFLOW.md": `# Workflow: Research to Skill

Turning something you had to figure out into something nobody has to figure out
again.

1. \`awb research start --question "..."\` — bound the question before searching.
2. \`awb research attempt <id> --tried "..." --result ...\` after each try.
   Record the failures; they are what save the next person time.
3. \`awb research conclude <id> --text "..."\` when the question is answered.
4. \`awb memory approve <proposal-id>\` — you decide whether it becomes knowledge.
5. If the approach is worth repeating, write it up as a skill:
   \`skills/<id>/SKILL.md\` for the method and \`skills/<id>/skill.json\` for the
   contract. \`useWhen\` is the field that lets an agent pick it later, so write
   that one for a reader who does not already know what the skill does.
6. \`awb validate\` — a malformed contract is an error, a missing one a warning.
7. If it should be shared, open a pull request against the distribution. The
   maintainer decides what the whole team carries.

Do not promote after one success. A skill is a claim that the approach works
again.
`
};

// Asked in English and stored in English; the agent conducts the interview in
// whatever language the user speaks and records the answers here.
export const ONBOARDING_QUESTIONS = [
  { id: "name", kind: "text", required: true, prompt: "What should I call you?" },
  {
    id: "role",
    kind: "choice",
    required: true,
    catalog: "roles",
    prompt: "Which role best describes your main work here?"
  },
  {
    id: "language",
    kind: "text",
    required: true,
    prompt: "Which language should I write and talk to you in?"
  },
  {
    id: "responsibilities",
    kind: "list",
    required: true,
    prompt: "What are you responsible for day to day?"
  },
  {
    id: "systems",
    kind: "list",
    required: false,
    prompt: "Which systems, products, or codebases do you own or touch most?"
  },
  {
    id: "skills",
    kind: "list",
    required: false,
    catalog: "skills",
    prompt: "Which of these skills do you expect to need regularly?"
  },
  {
    id: "principles",
    kind: "list",
    required: false,
    prompt: "How do you prefer work to be done? Anything I should always do?"
  },
  {
    id: "constraints",
    kind: "list",
    required: false,
    prompt: "Anything I must never do, or must ask you before doing?"
  }
];
